# Site settings
title: Coding for dummies
header-img: img/home-bg.png
email: mikegylling@yahoo.com
copyright_name: rgylling
description: > # this means to ignore newlines until "baseurl:"
  The road to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rgylling
learn_profile: rgylling
email_username: mikegylling@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
